name: MXD-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - wget
  - curl
  - bakta=1.8.2
  - blast
  - diamond
  - hmmer
  - prodigal        
  - pyrodigal        
  - trnascan-se
  - aragorn
  - infernal
  - seqkit
  - checkm-genome
  - pigz
  - pbzip2
  - sra-tools        
  - ncbi-datasets-cli 
  - biopython
  - pandas
  - numpy
  - tqdm
  - alive-progress=3.0.1
  - about-time
  - pyyaml
  - geopy
  - geopandas
  - shapely
  - pyproj
  - fiona
  - rtree
  - antismash=7.1.0
  - pyhmmer=0.10.0
  - sqlalchemy
  - goatools
  - fastapi
  - uvicorn
  - pip:
    - habanero
    - plotly
